import React, { useState } from 'react';
import { FileText, RefreshCw, Printer, ShieldCheck } from 'lucide-react';

function IsmsReport() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportData, setReportData] = useState(null);

  const handleGenerate = () => {
    setIsGenerating(true);
    // Simulate API delay fetching SIEM data
    setTimeout(() => {
      setReportData({
        date: new Date().toLocaleDateString(),
        threats: [
          { asset: 'Web Server (10.0.2.15)', threat: 'High Shannon Entropy Payload', cve: 'Defense Evasion', impact: 'High' },
          { asset: 'VPN Gateway (10.0.1.20)', threat: 'Password Spraying (Event 4625)', cve: 'Credential Access', impact: 'Critical' },
          { asset: 'Windows AD (10.0.5.10)', threat: 'Suspicious PowerShell Execution', cve: 'Execution', impact: 'Critical' }
        ],
        risks: [
          { id: 'RSK-01', desc: 'Unauthorized lateral movement via compromised AD credentials', likelihood: 'High', impact: 'Critical', level: 'Critical' },
          { id: 'RSK-02', desc: 'Fileless malware executing via encoded PowerShell scripts', likelihood: 'Medium', impact: 'High', level: 'High' },
          { id: 'RSK-03', desc: 'Advanced obfuscation bypassing standard pattern matching (DGA)', likelihood: 'Medium', impact: 'Medium', level: 'Medium' }
        ]
      });
      setIsGenerating(false);
    }, 1500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="h-full p-4 flex flex-col gap-6 overflow-y-auto print:overflow-visible print:p-0 print:block">
      {/* Header & Controls (Hidden when printing) */}
      <header className="flex justify-between items-center glass-panel p-6 print:hidden">
        <div className="flex items-center gap-3">
          <FileText className="text-siem-primary" size={28} />
          <h1 className="text-2xl font-bold">Information Security Management System (ISMS) Report Generator</h1>
        </div>
        
        <div className="flex gap-4">
          <button 
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-4 py-2 bg-siem-primary/20 text-blue-400 border border-siem-primary/30 rounded-lg hover:bg-siem-primary/30 transition-colors"
          >
            <RefreshCw size={18} className={isGenerating ? "animate-spin" : ""} />
            {isGenerating ? "Generating..." : "Generate Report"}
          </button>
          
          <button 
            onClick={handlePrint}
            disabled={!reportData}
            className={`flex items-center gap-2 px-4 py-2 border rounded-lg transition-colors ${
              reportData ? 'bg-white/10 text-white border-siem-border hover:bg-white/20' : 'bg-gray-800 text-gray-500 border-gray-700 cursor-not-allowed'
            }`}
          >
            <Printer size={18} /> Export to PDF
          </button>
        </div>
      </header>

      {/* Document Layout */}
      {reportData ? (
        <div id="printable-report" className="bg-white text-black p-12 max-w-4xl mx-auto shadow-2xl w-full print:p-0 print:shadow-none print:max-w-none print:w-full print:mx-0">
          
          {/* 1. Cover Page */}
          <div className="border-b-4 border-blue-900 pb-10 mb-10 text-center mt-10 print:break-after-page print:mt-32 print:border-b-2">
            <h1 className="text-4xl font-extrabold text-blue-900 mb-4 uppercase tracking-widest">ISMS Compliance Report</h1>
            <h2 className="text-2xl font-semibold text-gray-700 mb-12">ISO/IEC 27001:2022 Framework Assessment</h2>
            
            <div className="inline-block text-left bg-gray-50 p-6 border border-gray-200 rounded-lg shadow-sm">
              <table className="w-full text-gray-800">
                <tbody>
                  <tr><td className="font-bold py-3 pr-8 border-b border-gray-200">Project Name:</td><td className="py-3 border-b border-gray-200">Educational SIEM Platform FYP</td></tr>
                  <tr><td className="font-bold py-3 pr-8 border-b border-gray-200">Prepared By:</td><td className="py-3 border-b border-gray-200">[Student Name]</td></tr>
                  <tr><td className="font-bold py-3 pr-8 border-b border-gray-200">Student ID:</td><td className="py-3 border-b border-gray-200">[Student ID]</td></tr>
                  <tr><td className="font-bold py-3 pr-8">Date Generated:</td><td className="py-3">{reportData.date}</td></tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* 2. Executive Summary */}
          <div className="mb-10">
            <h3 className="text-xl font-bold text-blue-900 border-b-2 border-gray-300 pb-2 mb-4">1. Executive Summary</h3>
            <p className="text-gray-800 leading-relaxed text-justify">
              This document serves as the formal compliance and security posture report generated by the SIEM platform. 
              It evaluates the current threat landscape against the organization's critical assets and assesses the 
              effectiveness of implemented security controls mapped to the ISO/IEC 27001:2022 requirements. The data contained 
              herein is synthesized from real-time log ingestion, active threat hunting feeds, and dynamic risk scoring mechanisms.
            </p>
          </div>

          {/* 3. Threat & Vulnerability Analysis */}
          <div className="mb-10 print:break-inside-avoid">
            <h3 className="text-xl font-bold text-blue-900 border-b-2 border-gray-300 pb-2 mb-4">2. Threat & Vulnerability Analysis</h3>
            <table className="w-full border-collapse border border-gray-300 text-sm">
              <thead className="bg-gray-100 text-gray-800">
                <tr>
                  <th className="border border-gray-300 p-3 text-left font-bold">Asset</th>
                  <th className="border border-gray-300 p-3 text-left font-bold">Threat (Alert Name)</th>
                  <th className="border border-gray-300 p-3 text-left font-bold">Vulnerability (CVE ID)</th>
                  <th className="border border-gray-300 p-3 text-left font-bold">Impact</th>
                </tr>
              </thead>
              <tbody>
                {reportData.threats.map((t, idx) => (
                  <tr key={idx} className="hover:bg-gray-50">
                    <td className="border border-gray-300 p-3 font-semibold text-gray-700">{t.asset}</td>
                    <td className="border border-gray-300 p-3 text-gray-800">{t.threat}</td>
                    <td className="border border-gray-300 p-3 font-mono font-bold text-red-600">{t.cve}</td>
                    <td className="border border-gray-300 p-3 text-gray-800">{t.impact}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* 4. Risk Assessment */}
          <div className="mb-10 print:break-inside-avoid">
            <h3 className="text-xl font-bold text-blue-900 border-b-2 border-gray-300 pb-2 mb-4">3. Risk Assessment Registry</h3>
            <table className="w-full border-collapse border border-gray-300 text-sm">
              <thead className="bg-gray-100 text-gray-800">
                <tr>
                  <th className="border border-gray-300 p-3 text-left font-bold w-20">Risk ID</th>
                  <th className="border border-gray-300 p-3 text-left font-bold">Risk Description</th>
                  <th className="border border-gray-300 p-3 text-left font-bold w-24">Likelihood</th>
                  <th className="border border-gray-300 p-3 text-left font-bold w-24">Impact</th>
                  <th className="border border-gray-300 p-3 text-left font-bold w-24 text-center">Risk Level</th>
                </tr>
              </thead>
              <tbody>
                {reportData.risks.map((r, idx) => (
                  <tr key={idx} className="hover:bg-gray-50">
                    <td className="border border-gray-300 p-3 font-mono font-bold text-gray-600">{r.id}</td>
                    <td className="border border-gray-300 p-3 text-gray-800">{r.desc}</td>
                    <td className="border border-gray-300 p-3 text-gray-800">{r.likelihood}</td>
                    <td className="border border-gray-300 p-3 text-gray-800">{r.impact}</td>
                    <td className="border border-gray-300 p-3 font-bold text-center">
                      <span className={`px-2 py-1 rounded text-white text-xs ${
                        r.level === 'Critical' ? 'bg-red-600' : 
                        r.level === 'High' ? 'bg-orange-500' : 'bg-yellow-500'
                      }`}>
                        {r.level}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* 5. Security Controls */}
          <div className="mb-10 print:break-inside-avoid">
            <h3 className="text-xl font-bold text-blue-900 border-b-2 border-gray-300 pb-2 mb-4">4. ISO/IEC 27001 Security Controls (Active)</h3>
            <ul className="list-disc pl-5 space-y-3 text-gray-800">
              <li><strong>A.8.12 Data Leakage Prevention:</strong> Network traffic analysis and payload inspection active on core switches.</li>
              <li><strong>A.8.15 Logging:</strong> Centralized SIEM log aggregation active for all critical infrastructure endpoints.</li>
              <li><strong>A.8.16 Monitoring Activities:</strong> Real-time IDS/IPS alerts configured for high-severity threat signatures.</li>
              <li><strong>A.5.17 Authentication Information:</strong> Role-Based Access Control (RBAC) enforced on the SIEM management console.</li>
            </ul>
          </div>

          {/* 6. Incident Response */}
          <div className="mb-10 print:break-inside-avoid">
            <h3 className="text-xl font-bold text-blue-900 border-b-2 border-gray-300 pb-2 mb-4">5. Incident Response & Monitoring</h3>
            <p className="text-gray-800 leading-relaxed text-justify">
              The SIEM platform currently provides 24/7 centralized log management and real-time alerting. Active incidents 
              are automatically routed to the Threat Hunting dashboard, ensuring Mean Time to Detect (MTTD) and Mean Time to Respond (MTTR) 
              align with organizational SLAs and compliance requirements. System health and network flows are monitored continuously.
            </p>
          </div>

          {/* Footer */}
          <div className="text-center text-gray-500 text-xs mt-16 border-t border-gray-200 pt-6 font-mono">
            <p>End of Report | Auto-generated by Educational SIEM Platform v1.0</p>
            <p className="mt-1">CONFIDENTIAL - DO NOT DISTRIBUTE WITHOUT AUTHORIZATION</p>
          </div>

        </div>
      ) : (
        <div className="glass-panel flex-1 flex flex-col items-center justify-center text-gray-400 print:hidden">
          <ShieldCheck size={64} className="mb-4 text-gray-600" />
          <h2 className="text-xl font-bold mb-2">No Report Generated</h2>
          <p className="text-sm">Click "Generate Report" to compile the latest SIEM compliance data.</p>
        </div>
      )}
    </div>
  );
}

export default IsmsReport;
